### ISSUE TITLE
Fail to read the file and run training

### ISSUE THREAD

**Issue by tobegit3hub** [wenxinxu/resnet_in_tensorflow#10]
I have followed the REAME and get this error while running training.

<img width="973" alt="screen shot 2017-11-02 at 10 27 17 am" src="https://user-images.githubusercontent.com/2715000/32306905-8dcdc450-bf4b-11e7-997e-82bdba2b34f9.png">

**Comment by wenxinxu** [comment]
If you change the working directory and run python cifar10_train.py instead of "./cifar10_train.py", the maybe_download_and_extract() will download the dataset in the correct directory.

**Comment by tobegit3hub** [comment]
Thanks for response.

It turns out to be my problem when downloading the corrupt files of cifar10. Not an issue and close now.
